import { Link } from "@/i18n/navigation";
import type { Locale } from "@/i18n/routing";
export const metadata = { title: "Kalivoa — Extension privacy / Confidentialité" };
export default async function ExtensionPrivacy({ params }: { params: Promise<{ locale: Locale }> }) {
  const { locale } = await params;
  const fr = locale === "fr";
  const sections = fr ? [
    ["Finalité", "L’extension Kalivoa sert à capturer une zone de ticket de pari et à envoyer un lot de captures vers le Scan Kalivoa pour vérification avant import. Elle ne place aucun pari."],
    ["Données locales", "Les images recadrées, leur identifiant, la date de capture et le nom de domaine de la page sont conservés dans le navigateur. L’extension ne lit pas l’historique de navigation, ne conserve pas de mot de passe ni de cookie bookmaker et ne surveille pas les pages en continu."],
    ["Envoi et analyse", "Aucune capture n’est envoyée automatiquement. Après ton clic sur Envoyer à Kalivoa, kalivoa.com reçoit les captures et leurs métadonnées. Une session Kalivoa est nécessaire pour les analyser. Les images sont transmises au fournisseur IA configuré (Google ou Anthropic) pour extraire les paris. Les données extraites sont enregistrées dans ton compte après confirmation de l’import. Les résultats d’analyse nécessaires à la reprise sont conservés temporairement pendant sept jours."],
    ["Conservation et suppression", "Les captures locales restent disponibles jusqu’à leur suppression manuelle ou au nettoyage après validation ou import. Les captures échouées peuvent rester pour permettre une nouvelle tentative. Tu peux supprimer une capture ou toutes les captures depuis l’extension. Les images ne sont pas conservées par Kalivoa après analyse, sauf si tu actives explicitement une fonction de conservation, comme la contribution à l’amélioration du Scan ou une preuve de certification, selon ses conditions propres."],
    ["Mesure d’utilisation", "Des événements techniques (ouverture, capture, suppression, envoi, réussite ou échec du Scan) sont utilisés pour mesurer et améliorer le service. Les événements locaux sont transmis à Kalivoa lors de l’envoi du lot. Ils ne contiennent pas les images ni le contenu des tickets. Les données ne sont pas vendues et ne servent pas à la publicité."],
    ["Permissions", "activeTab autorise temporairement la capture de l’onglet après ton action ; scripting affiche l’outil de sélection. Seul kalivoa.com peut communiquer avec l’extension. Aucun code distant n’est exécuté."],
    ["Contact et droits", "Pour une demande d’accès ou de suppression de données, contacte contact.kalivoa@gmail.com. La politique générale de Kalivoa complète cette page. Dernière mise à jour : 30 septembre 2026."],
  ] : [
    ["Purpose", "Kalivoa captures a selected bet ticket area and sends a batch to Kalivoa Scan for review before import. It does not place bets."],
    ["Local data", "Cropped images, identifiers, capture dates and page hostnames are stored in your browser. The extension does not read browsing history, store bookmaker credentials or cookies, or continuously monitor pages."],
    ["Transfer and analysis", "Captures are never uploaded automatically. Clicking Send to Kalivoa transfers captures and their metadata to kalivoa.com. Analysis requires a Kalivoa session. Images are sent to the configured AI provider (Google or Anthropic) to extract bets. Extracted bets are saved after you confirm the import. Temporary analysis results used for resuming are retained for seven days."],
    ["Retention and deletion", "Local captures remain until manually deleted or cleaned up after review or import. Failed captures may remain for retry. Delete individual captures or all captures in the extension. Kalivoa does not retain images after analysis unless you explicitly enable a retention feature, such as Scan improvement contributions or certification evidence, under its own terms."],
    ["Usage measurement", "Technical events (opening, capturing, deleting, sending, Scan success or failure) help measure and improve the service. Local events are sent to Kalivoa when you send a batch. They contain no images or ticket contents. Data is not sold or used for advertising."],
    ["Permissions", "activeTab temporarily allows capture after your action; scripting displays the selection tool. Only kalivoa.com can communicate with the extension. No remote code is executed."],
    ["Contact and rights", "For data access or deletion requests, contact contact.kalivoa@gmail.com. Kalivoa’s general privacy policy also applies. Last updated: September 30, 2026."],
  ];
  return <article className="kalivoa-content-frame max-w-3xl space-y-8 py-12"><Link href="/extension" className="text-sm text-primary">← {fr ? "Extension Chrome" : "Chrome extension"}</Link><h1 className="text-3xl font-semibold">{fr ? "Confidentialité de l’extension Kalivoa" : "Kalivoa extension privacy"}</h1>{sections.map(([title, text]) => <section key={title} className="space-y-3"><h2 className="text-xl font-semibold">{title}</h2><p className="text-sm leading-7 text-muted-foreground">{text}</p></section>)}<Link href="/privacy" className="inline-block text-primary underline">{fr ? "Politique générale de confidentialité" : "General privacy policy"}</Link></article>;
}
