import { ArrowDown, ArrowUp, ListNumbers } from "@phosphor-icons/react/dist/ssr";
import { movePublicBankroll } from "@/lib/actions/public-bankroll-settings";

export function PublicBankrollOrder({ bankrolls }: { bankrolls: Array<{ id: string; name: string; isPublic: boolean }> }) {
  if (!bankrolls.length) return null;
  return <section className="glass-card rounded-xl p-4 xl:col-span-12">
    <div className="flex items-start gap-3"><span className="flex size-11 shrink-0 items-center justify-center rounded-xl bg-primary/15 text-primary"><ListNumbers size={22} weight="fill" aria-hidden /></span><div><h2 className="text-sm font-semibold">Ordre de mes bankrolls publiques</h2><p className="mt-1 text-xs leading-relaxed text-muted-foreground">Choisis l’ordre affiché sur ton profil de tipster. Une bankroll masquée conserve sa position.</p></div></div>
    <ol className="mt-4 grid gap-2">{bankrolls.map((bankroll, index) => <li key={bankroll.id} className="flex min-h-12 items-center gap-3 rounded-xl border border-border bg-background/30 px-3"><span className="num flex size-7 shrink-0 items-center justify-center rounded-lg bg-muted text-xs font-bold">{index + 1}</span><span className="min-w-0 flex-1 truncate text-sm font-semibold">{bankroll.name}</span>{!bankroll.isPublic ? <span className="rounded-full bg-warning/10 px-2 py-1 text-[0.65rem] font-semibold text-warning">Masquée</span> : null}<div className="flex gap-1"><form action={movePublicBankroll}><input type="hidden" name="bankrollId" value={bankroll.id} /><input type="hidden" name="direction" value="up" /><button disabled={index === 0} aria-label={`Monter ${bankroll.name}`} className="flex size-9 items-center justify-center rounded-lg border border-border disabled:cursor-not-allowed disabled:opacity-30 hover:bg-muted"><ArrowUp size={16} aria-hidden /></button></form><form action={movePublicBankroll}><input type="hidden" name="bankrollId" value={bankroll.id} /><input type="hidden" name="direction" value="down" /><button disabled={index === bankrolls.length - 1} aria-label={`Descendre ${bankroll.name}`} className="flex size-9 items-center justify-center rounded-lg border border-border disabled:cursor-not-allowed disabled:opacity-30 hover:bg-muted"><ArrowDown size={16} aria-hidden /></button></form></div></li>)}</ol>
  </section>;
}
